openapi: 3.0.0
info:
  version: 1.0.0
  title: OAuth API
  description: API documentation for managing users with OAuth authentication using Google and GitHub.

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /auth/google:
    get:
      summary: Google OAuth login
      description: Initiate Google OAuth authentication.
      responses:
        '302':
          description: Redirect to Google for authentication

  /auth/google/callback:
    get:
      summary: Google OAuth callback
      description: Handle Google OAuth callback and return user info.
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /auth/github:
    get:
      summary: GitHub OAuth login
      description: Initiate GitHub OAuth authentication.
      responses:
        '302':
          description: Redirect to GitHub for authentication

  /auth/github/callback:
    get:
      summary: GitHub OAuth callback
      description: Handle GitHub OAuth callback and return user info.
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized

  /api/users:
    get:
      summary: Get all users
      security:
        - cookieAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error

  /api/user/{id}:
    get:
      summary: Get user by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error

    delete:
      summary: Delete user by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
        '500':
          description: Internal server error
    patch:
      summary: Partially update user by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
        '404':
          description: User not found
        '500':
          description: Internal server error

    put:
      summary: Fully update user by ID
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
        '201':
          description: User created
        '500':
          description: Internal server error

  /api/users:
    post:
      summary: Add new user
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '500':
          description: Internal server error


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: johndoe@example.com
        gender:
          type: string
          example: male
        bloodgroup:
          type: string
          example: O+

  securitySchemes:
    googleOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            email: Access user's email
            profile: Access user's profile

    githubOAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/authorize
          tokenUrl: https://github.com/login/oauth/access_token
          scopes:
            user: Access user's profile

    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken

security:
  - cookieAuth: []
